-- begin TESTING_QUESTION_AND_ANSWER
alter table TESTING_QUESTION_AND_ANSWER add constraint FK_TESTING_QUESTION_AND_ANSWER_ON_QUESTION foreign key (QUESTION_ID) references TESTING_QUESTION(ID)^
alter table TESTING_QUESTION_AND_ANSWER add constraint FK_TESTING_QUESTION_AND_ANSWER_ON_ANSWER foreign key (ANSWER_ID) references TESTING_ANSWER(ID)^
create index IDX_TESTING_QUESTION_AND_ANSWER_ON_QUESTION on TESTING_QUESTION_AND_ANSWER (QUESTION_ID)^
create index IDX_TESTING_QUESTION_AND_ANSWER_ON_ANSWER on TESTING_QUESTION_AND_ANSWER (ANSWER_ID)^
-- end TESTING_QUESTION_AND_ANSWER
